name = "graffiti-api"
main = "worker/worker.js"
compatibility_date = "2024-06-20"

[[d1_databases]]
binding = "DB"
database_name = "graffiti"
database_id = "<copy-from-dashboard>"

[[kv_namespaces]]
binding = "KV"
id = "<copy-from-dashboard>"
